// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: protobuf/schema.proto

package schema

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SchemaClient is the client API for Schema service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchemaClient interface {
	RetrieveSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RetrieveSchemaReply, error)
	RetrieveTable(ctx context.Context, in *RetrieveTableRequest, opts ...grpc.CallOption) (*RetrieveTableReply, error)
}

type schemaClient struct {
	cc grpc.ClientConnInterface
}

func NewSchemaClient(cc grpc.ClientConnInterface) SchemaClient {
	return &schemaClient{cc}
}

func (c *schemaClient) RetrieveSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RetrieveSchemaReply, error) {
	out := new(RetrieveSchemaReply)
	err := c.cc.Invoke(ctx, "/schema.Schema/RetrieveSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaClient) RetrieveTable(ctx context.Context, in *RetrieveTableRequest, opts ...grpc.CallOption) (*RetrieveTableReply, error) {
	out := new(RetrieveTableReply)
	err := c.cc.Invoke(ctx, "/schema.Schema/RetrieveTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchemaServer is the server API for Schema service.
// All implementations must embed UnimplementedSchemaServer
// for forward compatibility
type SchemaServer interface {
	RetrieveSchema(context.Context, *Empty) (*RetrieveSchemaReply, error)
	RetrieveTable(context.Context, *RetrieveTableRequest) (*RetrieveTableReply, error)
	mustEmbedUnimplementedSchemaServer()
}

// UnimplementedSchemaServer must be embedded to have forward compatible implementations.
type UnimplementedSchemaServer struct {
}

func (UnimplementedSchemaServer) RetrieveSchema(context.Context, *Empty) (*RetrieveSchemaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveSchema not implemented")
}
func (UnimplementedSchemaServer) RetrieveTable(context.Context, *RetrieveTableRequest) (*RetrieveTableReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveTable not implemented")
}
func (UnimplementedSchemaServer) mustEmbedUnimplementedSchemaServer() {}

// UnsafeSchemaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchemaServer will
// result in compilation errors.
type UnsafeSchemaServer interface {
	mustEmbedUnimplementedSchemaServer()
}

func RegisterSchemaServer(s grpc.ServiceRegistrar, srv SchemaServer) {
	s.RegisterService(&Schema_ServiceDesc, srv)
}

func _Schema_RetrieveSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).RetrieveSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.Schema/RetrieveSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).RetrieveSchema(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schema_RetrieveTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).RetrieveTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.Schema/RetrieveTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).RetrieveTable(ctx, req.(*RetrieveTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Schema_ServiceDesc is the grpc.ServiceDesc for Schema service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Schema_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schema.Schema",
	HandlerType: (*SchemaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveSchema",
			Handler:    _Schema_RetrieveSchema_Handler,
		},
		{
			MethodName: "RetrieveTable",
			Handler:    _Schema_RetrieveTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/schema.proto",
}
