// protoc --go_out=./schema --go-grpc_out=./schema .\protobuf\schema.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: protobuf/schema.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{0}
}

type RetrieveSchemaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schema []string `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty"`
}

func (x *RetrieveSchemaReply) Reset() {
	*x = RetrieveSchemaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_schema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveSchemaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveSchemaReply) ProtoMessage() {}

func (x *RetrieveSchemaReply) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveSchemaReply.ProtoReflect.Descriptor instead.
func (*RetrieveSchemaReply) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveSchemaReply) GetSchema() []string {
	if x != nil {
		return x.Schema
	}
	return nil
}

type RetrieveTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schema string `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *RetrieveTableRequest) Reset() {
	*x = RetrieveTableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_schema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveTableRequest) ProtoMessage() {}

func (x *RetrieveTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveTableRequest.ProtoReflect.Descriptor instead.
func (*RetrieveTableRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveTableRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type RetrieveTableReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table []string `protobuf:"bytes,1,rep,name=table,proto3" json:"table,omitempty"`
}

func (x *RetrieveTableReply) Reset() {
	*x = RetrieveTableReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_schema_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveTableReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveTableReply) ProtoMessage() {}

func (x *RetrieveTableReply) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveTableReply.ProtoReflect.Descriptor instead.
func (*RetrieveTableReply) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveTableReply) GetTable() []string {
	if x != nil {
		return x.Table
	}
	return nil
}

var File_protobuf_schema_proto protoreflect.FileDescriptor

var file_protobuf_schema_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2d, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x2e, 0x0a, 0x14, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x2a, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x32, 0x95, 0x01, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x3e,
	0x0a, 0x0e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x12, 0x0d, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x1b, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4b,
	0x0a, 0x0d, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x1c, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x3b, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_schema_proto_rawDescOnce sync.Once
	file_protobuf_schema_proto_rawDescData = file_protobuf_schema_proto_rawDesc
)

func file_protobuf_schema_proto_rawDescGZIP() []byte {
	file_protobuf_schema_proto_rawDescOnce.Do(func() {
		file_protobuf_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_schema_proto_rawDescData)
	})
	return file_protobuf_schema_proto_rawDescData
}

var file_protobuf_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_schema_proto_goTypes = []interface{}{
	(*Empty)(nil),                // 0: schema.Empty
	(*RetrieveSchemaReply)(nil),  // 1: schema.RetrieveSchemaReply
	(*RetrieveTableRequest)(nil), // 2: schema.RetrieveTableRequest
	(*RetrieveTableReply)(nil),   // 3: schema.RetrieveTableReply
}
var file_protobuf_schema_proto_depIdxs = []int32{
	0, // 0: schema.Schema.RetrieveSchema:input_type -> schema.Empty
	2, // 1: schema.Schema.RetrieveTable:input_type -> schema.RetrieveTableRequest
	1, // 2: schema.Schema.RetrieveSchema:output_type -> schema.RetrieveSchemaReply
	3, // 3: schema.Schema.RetrieveTable:output_type -> schema.RetrieveTableReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_schema_proto_init() }
func file_protobuf_schema_proto_init() {
	if File_protobuf_schema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_schema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveSchemaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_schema_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveTableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_schema_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveTableReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_schema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_schema_proto_goTypes,
		DependencyIndexes: file_protobuf_schema_proto_depIdxs,
		MessageInfos:      file_protobuf_schema_proto_msgTypes,
	}.Build()
	File_protobuf_schema_proto = out.File
	file_protobuf_schema_proto_rawDesc = nil
	file_protobuf_schema_proto_goTypes = nil
	file_protobuf_schema_proto_depIdxs = nil
}
